name: My First Workflow

on: [push,fork]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              
            - name: Welcome message
              run: echo "My First Github actions practice"

            - name: List files
              run: ls
            
            - name: Read file
              run: cat README.md
              